#cloud-config
package_update: true
packages:
  - docker.io
  - docker-compose
runcmd:
  - cd /
  - mkdir influxdb
  - touch /acme.json
  - chmod 600 /acme.json
  - cd /
  - wget https://storage.com/docker-compose.yml # Change for the URl you have hosted your file  
  - docker-compose up -d
